version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
  - doc/*
  - readme.md
  - license.md

nuget:
  disable_publish_on_pr: true

install:
- cmd: git submodule update --init --recursive

before_build:
- cmd: msbuild Confuser2.sln /t:Restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  project: Confuser2.sln
  verbosity: minimal

after_build:
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx-CLI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location ConfuserEx\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx-GUI.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location
- pwsh: >-
    Push-Location Confuser.CLI\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml";
    Pop-Location;
    Push-Location ConfuserEx\bin\$env:CONFIGURATION;
    . 7z a ..\..\..\ConfuserEx.zip "-xr!*.pdb" "-xr!*.xml" -y;
    Pop-Location

artifacts:
- path: ConfuserEx*.zip
- path: Confuser.MSBuild.Tasks/bin/Release/*.nupkg
  name: ConfuserEx.MSBuild

for:
-
  branches:
    except:
      - master

  build:
    publish_nuget: false

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: "ConfuserEx $(APPVEYOR_REPO_TAG_NAME) Release"
  auth_token:
    secure: NTT+Z1zBxbj+w8jroqhYJnI2urxSt0gq3MUmDavUPVKZL+YX4krR4xJQ5OmHYhcG
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: yqARg8GA5EIFGPVpYPZeS3I5gjsByMvYLVfXylpC9mF33W4Z40tAmE9q0/yf2Xne
  on:
    APPVEYOR_REPO_TAG: true
